
name: Deploy with Maven & Packer

on:
  pull_request_target:
    types: [ closed ]
    branches:
      - main

jobs:
  deploy:
    name: packer build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target' && github.event.action == 'closed' && github.event.pull_request.merged
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build application artifact
        run: mvn package -DskipTests

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Packer Init
        run: packer init .
#
#      - name: Packer Build
#        run: packer build .

      - name: Get new AMI id
        run: AMI_ID=$(aws ec2 describe-images --filters "Name=name,Values=csye6225_*" --query "reverse(sort_by(Images, &CreationDate))[:1].ImageId")

      - name: Create a new launch template
        run: aws ec2 create-launch-template-version --launch-template-id ${{ secrets.LAUNCH_TEMPLATE_ID }} --source-version 1 --version-description "Update AMI ID to latest" --launch-template-data "{\"ImageId\":\"$AMI_ID\"}"

      - name: Autoscaling group instance refresh
        run: aws autoscaling start-instance-refresh --auto-scaling-group-name ${{ secrets.ASG_NAME }}

